[NCL-8044] Add git backend switching
project-ncl/repour pull request #628
Opened 2023-12-11 19:04 UTC by pkocandr

### All Submissions:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/repour/wiki/Changelog) for your change?
* [ ] Have you added unit tests for your change?

2023-12-13 12:22 UTC, pkocandr commented
retest this please

2023-12-13 13:36 UTC, pkocandr commented
retest this please

2023-12-13 20:36 UTC, thescouser89 commented
retest this please

2023-12-13 22:54 UTC, pkocandr commented
retest this please

2024-01-05 15:53 UTC, thescouser89 requested changes

2024-01-05 15:53 UTC, thescouser89 commented on repour/server/endpoint/internal_scm_gitlab.py
> +        return token_file.read()
You might want to do:
```python
return token_file.read().strip()
```

to remove any newline at the end of the token when read in the file.

2024-01-05 15:54 UTC, thescouser89 commented on repour/server/endpoint/internal_scm_gitlab.py
> +        return token_file.read()
meh if that's the only issue I could find, I'll just merge it and create another PR for it.

2024-01-05 15:54 UTC, thescouser89 approved these changes

2024-01-05 15:54 UTC, merged